title: "GEMINI INVOICE"
from: "Gemini, Inc."
logo: "gemini-invoice-picture-01.png"
account_number: "1234567890"
routing_number: "987654321"
payment_instructions: "Please make payment via direct deposit to the following account:"
