title: "Invoice"
from: "Dutchesz Gemini\n1234 Delicious St\nCity, State 99999"
logo: "gemini-invoice-picture-01.png"
account_number: "1234567890"
routing_number: "987654321"
payment_instructions: "Please make payment via bank transfer using the account details below."
