title: "Invoice"
from: "Your Company Name\n123 Business Street\nCity, State 12345\nCountry"
logo: "logo.png"
account_number: "1234567890"
routing_number: "987654321"
payment_instructions: "Please make payment via bank transfer using the account details below."
